device: cuda
eval:
  batch_size: 1
  metrics:
  - recovery
  - perplexity
  - sc_eternafold
  - sc_rhofold
  n_samples: 8
  num_workers: 0
  out_dir: runs/benchmark_full
  pin_memory: true
  save_designs: false
  temperature: 1.0
  wandb:
    enable: true
    entity: null
    project: DPO-RNA
    run_name: null
    tags:
    - bench
    - gRNAde
    - full_eval
    - self_consistency
featurizer:
  device: cpu
  distance_eps: 0.001
  max_num_conformers: 1
  noise_scale: 0.0
  num_posenc: 32
  num_rbf: 32
  radius: 0.0
  split: val
  top_k: 32
model:
  drop_rate: 0.5
  edge_h_dim:
  - 64
  - 4
  edge_in_dim:
  - 131
  - 3
  name: AutoregressiveMultiGNNv1
  node_h_dim:
  - 128
  - 16
  node_in_dim:
  - 15
  - 4
  num_layers: 4
  out_dim: 4
paths:
  checkpoints:
  - name: BASE_gRNAde_1state_das
    path: checkpoints/gRNAde_ARv1_1state_das.h5
  processed_pt: data/processed.pt
  split_name: val
  split_pt: data/das_split.pt
seed: 0
